name: Test

on:
  pull_request:
    branches: [main]

env:
  ZULIP_API_KEY: ${{secrets.ZULIP_API_KEY}}
  ZULIP_EMAIL: ${{secrets.ZULIP_EMAIL}}
  ZULIP_SITE: ${{secrets.ZULIP_SITE}}
  SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
  SUPABASE_URL: ${{secrets.SUPABASE_URL}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.0
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pytest
        run: pytest
